# Generated by Django 3.0.3 on 2020-04-04 17:59

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrdenes',
            fields=[
                ('orden', models.IntegerField(blank=True, db_index=True, verbose_name='Número de órden')),
                ('descripcion', models.TextField()),
                ('fecha_ingreso', models.DateTimeField(blank=True, editable=False)),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('Creado', 'Creado'), ('Asignado', 'Asignado'), ('Finalizado', 'Finalizado'), ('Entregado', 'Entregado'), ('Despachado', 'Despachado'), ('Enviado', 'Enviado')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('ubicacion', models.CharField(choices=[('Secretaria', 'Secretaria'), ('Fortex Nueva', 'Fortex Nueva'), ('Fortex Vieja', 'Fortex Vieja'), ('Cliente', 'Cliente'), ('Verniciatura', 'Verniciatura'), ('Control Calidad', 'Control Calidad'), ('Montaje', 'Montaje'), ('Diseño gráfico', 'Diseño gráfico')], max_length=20)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('usuarios', models.CharField(max_length=35, null=True, verbose_name='Creado por ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical ordenes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('orden', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de órden')),
                ('descripcion', models.TextField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('Creado', 'Creado'), ('Asignado', 'Asignado'), ('Finalizado', 'Finalizado'), ('Entregado', 'Entregado'), ('Despachado', 'Despachado'), ('Enviado', 'Enviado')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('ubicacion', models.CharField(choices=[('Secretaria', 'Secretaria'), ('Fortex Nueva', 'Fortex Nueva'), ('Fortex Vieja', 'Fortex Vieja'), ('Cliente', 'Cliente'), ('Verniciatura', 'Verniciatura'), ('Control Calidad', 'Control Calidad'), ('Montaje', 'Montaje'), ('Diseño gráfico', 'Diseño gráfico')], max_length=20)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('usuarios', models.CharField(max_length=35, null=True, verbose_name='Creado por ')),
            ],
        ),
    ]
