# Generated by Django 3.0.3 on 2020-04-24 00:13

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrdenes',
            fields=[
                ('orden', models.IntegerField(blank=True, db_index=True, verbose_name='Número de órden')),
                ('descripcion', models.TextField()),
                ('fecha_ingreso', models.DateTimeField(blank=True, editable=False)),
                ('estado', models.CharField(choices=[('Ricevuto', 'Ricevuto'), ('Creato', 'Creato'), ('Assegnato', 'Assegnato'), ('Completato', 'Completato'), ('Consegnato', 'Consegnato'), ('Spedito', 'Spedito'), ('Inviato', 'Inviato')], max_length=20)),
                ('cantidad_recibida', models.PositiveIntegerField(null=True)),
                ('ubicacion', models.CharField(choices=[('Segretaria', 'Segretaria'), ('Fortex Nuova', 'Fortex Nuova'), ('Fortex Vecchia', 'Fortex Vecchia'), ('Cliente', 'Cliente'), ('Verniciatura', 'Verniciatura'), ('Controlo Qualità', 'Controlo Qualità'), ('Montaggio', 'Montaggio'), ('Graphic Design', 'Graphic Design')], max_length=20)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('cantidadEntregada', models.IntegerField(blank=True, null=True)),
                ('telaio', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical ordenes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('orden', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de órden')),
                ('descripcion', models.TextField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Ricevuto', 'Ricevuto'), ('Creato', 'Creato'), ('Assegnato', 'Assegnato'), ('Completato', 'Completato'), ('Consegnato', 'Consegnato'), ('Spedito', 'Spedito'), ('Inviato', 'Inviato')], max_length=20)),
                ('cantidad_recibida', models.PositiveIntegerField(null=True)),
                ('ubicacion', models.CharField(choices=[('Segretaria', 'Segretaria'), ('Fortex Nuova', 'Fortex Nuova'), ('Fortex Vecchia', 'Fortex Vecchia'), ('Cliente', 'Cliente'), ('Verniciatura', 'Verniciatura'), ('Controlo Qualità', 'Controlo Qualità'), ('Montaggio', 'Montaggio'), ('Graphic Design', 'Graphic Design')], max_length=20)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('cantidadEntregada', models.IntegerField(blank=True, null=True)),
                ('telaio', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
