# Generated by Django 3.0.3 on 2020-04-04 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ordenes', '0002_auto_20200404_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordenes',
            name='usuarios',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por '),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por '),
        ),
    ]
