# Generated by Django 3.0.3 on 2020-04-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes', '0005_auto_20200405_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordenes',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
