# Generated by Django 3.0.3 on 2020-04-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes', '0006_auto_20200408_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordenes',
            name='ubicacion',
            field=models.CharField(choices=[('Secretaria', 'Secretaria'), ('Fortex Nueva', 'Fortex Nueva'), ('Fortex Vieja', 'Fortex Vieja'), ('Cliente', 'Cliente'), ('Verniciatura', 'Verniciatura'), ('Control Calidad', 'Control Calidad'), ('Montaje', 'Montaje'), ('Diseño gráfico', 'Diseño gráfico'), ('Cliente', 'Cliente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='ubicacion',
            field=models.CharField(choices=[('Secretaria', 'Secretaria'), ('Fortex Nueva', 'Fortex Nueva'), ('Fortex Vieja', 'Fortex Vieja'), ('Cliente', 'Cliente'), ('Verniciatura', 'Verniciatura'), ('Control Calidad', 'Control Calidad'), ('Montaje', 'Montaje'), ('Diseño gráfico', 'Diseño gráfico'), ('Cliente', 'Cliente')], max_length=20),
        ),
    ]
