# Generated by Django 3.0.3 on 2020-04-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes', '0007_auto_20200408_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordenes',
            name='telaio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='telaio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
