# Generated by Django 3.0.3 on 2020-04-20 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_auto_20200416_1649'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ordenes', '0008_auto_20200417_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordenes',
            name='asignado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aseggnato a '),
        ),
        migrations.AlterField(
            model_name='historicalordenes',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Ricevuto'), ('Creado', 'Creato'), ('Asignado', 'Assegnato'), ('Finalizado', 'Completato'), ('Entregado', 'Consegnato'), ('Despachado', 'Spedito'), ('Enviado', 'Inviato')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalordenes',
            name='producto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Productos.Productos', verbose_name='Prodotto'),
        ),
        migrations.AlterField(
            model_name='historicalordenes',
            name='ubicacion',
            field=models.CharField(choices=[('Secretaria', 'Segretaria'), ('Fortex Nueva', 'Fortex Nuova'), ('Fortex Vieja', 'Fortex Vecchia'), ('Cliente', 'Cliente'), ('Verniciatura', 'Verniciatura'), ('Control Calidad', 'Controlo Qualità'), ('Montaje', 'Montaggio'), ('Diseño gráfico', 'Graphic Design')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalordenes',
            name='usuarios',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creato'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asignado', to=settings.AUTH_USER_MODEL, verbose_name='Aseggnato a '),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Ricevuto'), ('Creado', 'Creato'), ('Asignado', 'Assegnato'), ('Finalizado', 'Completato'), ('Entregado', 'Consegnato'), ('Despachado', 'Spedito'), ('Enviado', 'Inviato')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Productos', verbose_name='Prodotto'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='ubicacion',
            field=models.CharField(choices=[('Secretaria', 'Segretaria'), ('Fortex Nueva', 'Fortex Nuova'), ('Fortex Vieja', 'Fortex Vecchia'), ('Cliente', 'Cliente'), ('Verniciatura', 'Verniciatura'), ('Control Calidad', 'Controlo Qualità'), ('Montaje', 'Montaggio'), ('Diseño gráfico', 'Graphic Design')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creato'),
        ),
    ]
