# Generated by Django 3.0.3 on 2020-04-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes', '0009_auto_20200420_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordenes',
            name='estado',
            field=models.CharField(choices=[('Ricevuto', 'Ricevuto'), ('Creato', 'Creato'), ('Assegnato', 'Assegnato'), ('Completato', 'Completato'), ('Consegnato', 'Consegnato'), ('Spedito', 'Spedito'), ('Inviato', 'Inviato')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalordenes',
            name='ubicacion',
            field=models.CharField(choices=[('Segretaria', 'Segretaria'), ('Fortex Nuova', 'Fortex Nuova'), ('Fortex Vecchia', 'Fortex Vecchia'), ('Cliente', 'Cliente'), ('Verniciatura', 'Verniciatura'), ('Controlo Qualità', 'Controlo Qualità'), ('Montaggio', 'Montaggio'), ('Graphic Design', 'Graphic Design')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='estado',
            field=models.CharField(choices=[('Ricevuto', 'Ricevuto'), ('Creato', 'Creato'), ('Assegnato', 'Assegnato'), ('Completato', 'Completato'), ('Consegnato', 'Consegnato'), ('Spedito', 'Spedito'), ('Inviato', 'Inviato')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='ubicacion',
            field=models.CharField(choices=[('Segretaria', 'Segretaria'), ('Fortex Nuova', 'Fortex Nuova'), ('Fortex Vecchia', 'Fortex Vecchia'), ('Cliente', 'Cliente'), ('Verniciatura', 'Verniciatura'), ('Controlo Qualità', 'Controlo Qualità'), ('Montaggio', 'Montaggio'), ('Graphic Design', 'Graphic Design')], max_length=20),
        ),
    ]
