# Generated by Django 3.0.3 on 2020-04-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'permissions': (('Administrador', 'Administrador'), ('Encargado', 'Encargado'), ('Pintor', 'Pintor'), ('Montaje', 'Montaje'), ('Calidad1', 'Calidad1'), ('Secretaria', 'Secretaria'), ('Stock', 'Stock'))},
        ),
    ]
