# Generated by Django 3.0.3 on 2020-04-04 17:59

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_organizacion', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion1', models.CharField(blank=True, max_length=150)),
                ('direccion2', models.CharField(blank=True, max_length=150)),
                ('ciudad', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tipo_cliente', models.CharField(choices=[('Oro', 'Oro'), ('Plata', 'Plata'), ('Bronce', 'Bronce')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalClientes',
            fields=[
                ('rut', models.IntegerField(db_index=True)),
                ('nombre_organizacion', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion1', models.CharField(blank=True, max_length=150)),
                ('direccion2', models.CharField(blank=True, max_length=150)),
                ('ciudad', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tipo_cliente', models.CharField(choices=[('Oro', 'Oro'), ('Plata', 'Plata'), ('Bronce', 'Bronce')], max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
