# Generated by Django 3.0.3 on 2020-04-04 17:59

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductos',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('preTratamiento', models.TextField(blank=True)),
                ('plasma', models.CharField(blank=True, max_length=50)),
                ('fondo', models.TextField(blank=True)),
                ('deposito', models.CharField(blank=True, max_length=150)),
                ('finitura', models.TextField(blank=True)),
                ('controlCalidad', models.CharField(blank=True, max_length=50)),
                ('embalaje', models.CharField(blank=True, max_length=50)),
                ('consideraciones', models.TextField(blank=True)),
                ('temperatura', models.IntegerField()),
                ('tiempo_horno', models.IntegerField()),
                ('fotos', models.TextField(blank=True, max_length=100)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('preTratamiento', models.TextField(blank=True)),
                ('plasma', models.CharField(blank=True, max_length=50)),
                ('fondo', models.TextField(blank=True)),
                ('deposito', models.CharField(blank=True, max_length=150)),
                ('finitura', models.TextField(blank=True)),
                ('controlCalidad', models.CharField(blank=True, max_length=50)),
                ('embalaje', models.CharField(blank=True, max_length=50)),
                ('consideraciones', models.TextField(blank=True)),
                ('temperatura', models.IntegerField()),
                ('tiempo_horno', models.IntegerField()),
                ('fotos', models.ImageField(blank=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Clientes')),
            ],
        ),
    ]
