# Generated by Django 3.0.3 on 2020-04-24 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        ('Clientes', '0001_initial'),
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='finitura',
            field=models.ManyToManyField(blank=True, to='Stock.Stock'),
        ),
        migrations.AddField(
            model_name='productos',
            name='fondo',
            field=models.ManyToManyField(blank=True, related_name='_productos_fondo_+', to='Stock.Stock'),
        ),
        migrations.AddField(
            model_name='productos',
            name='preTratamiento',
            field=models.ManyToManyField(blank=True, related_name='_productos_preTratamiento_+', to='Stock.Stock'),
        ),
        migrations.AddField(
            model_name='productos',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Clientes'),
        ),
    ]
