# Generated by Django 3.0.3 on 2020-04-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_auto_20200404_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductos',
            name='telaio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='telaio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
