# Generated by Django 3.0.3 on 2020-04-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_auto_20200404_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductos',
            name='telaio',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='telaio',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
