# Generated by Django 3.0.3 on 2020-04-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
        ('Productos', '0006_auto_20200404_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductos',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='historicalproductos',
            name='finitura',
        ),
        migrations.RemoveField(
            model_name='historicalproductos',
            name='fondo',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='deposito',
        ),
        migrations.AddField(
            model_name='productos',
            name='deposito',
            field=models.ManyToManyField(blank=True, max_length=150, related_name='_productos_deposito_+', to='Stock.Stock'),
        ),
        migrations.RemoveField(
            model_name='productos',
            name='finitura',
        ),
        migrations.AddField(
            model_name='productos',
            name='finitura',
            field=models.ManyToManyField(blank=True, to='Stock.Stock'),
        ),
        migrations.RemoveField(
            model_name='productos',
            name='fondo',
        ),
        migrations.AddField(
            model_name='productos',
            name='fondo',
            field=models.ManyToManyField(blank=True, related_name='_productos_fondo_+', to='Stock.Stock'),
        ),
    ]
