# Generated by Django 3.0.3 on 2020-04-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
        ('Productos', '0007_auto_20200416_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductos',
            name='preTratamiento',
        ),
        migrations.AddField(
            model_name='historicalproductos',
            name='deposito',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RemoveField(
            model_name='productos',
            name='deposito',
        ),
        migrations.AddField(
            model_name='productos',
            name='deposito',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RemoveField(
            model_name='productos',
            name='preTratamiento',
        ),
        migrations.AddField(
            model_name='productos',
            name='preTratamiento',
            field=models.ManyToManyField(blank=True, related_name='_productos_preTratamiento_+', to='Stock.Stock'),
        ),
    ]
