# Generated by Django 3.0.3 on 2020-04-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('unidades', models.SmallIntegerField(choices=[(1, 'Kgs.'), (2, 'Grs.'), (3, 'Ltrs.'), (4, 'Mltrs.')])),
                ('tipo_de_producto', models.CharField(blank=True, choices=[('Fondo', 'Fondo'), ('Finitura', 'Finitura'), ('Pre_tratamiento', 'Pre_tratamiento')], max_length=15, null=True)),
                ('proveedor', models.CharField(max_length=50)),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
