# Generated by Django 3.0.3 on 2020-04-24 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        ('Ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo_de_producto', models.CharField(blank=True, choices=[('Fondo', 'Fondo'), ('Finitura', 'Finitura'), ('Pre_tratamiento', 'Pre_tratamiento')], max_length=15, null=True)),
                ('proveedor', models.CharField(max_length=50)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_movimiento', models.BooleanField()),
                ('cantidad', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.Stock')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ordenes.Ordenes')),
            ],
        ),
    ]
